# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.2

pipelines:
  default:
    - step:
        script:
          - pip3 install pipenv
          - pipenv install --dev
          - pipenv run flake8 . --exclude dev.py,manage.py,__pycache__,__init__.py,migrations --max-line-length=100
