version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7
    ports:
      - "5674:5672"
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        LOGS_DIR: /var/log/hs-api
    env_file:
      - .env
    volumes:
      - ./:/opt/api/
    ports:
      - "8000:8000"
