FROM jfloff/alpine-python:3.7

RUN /bin/bash -c 'mkdir -p "/var/log/hs-api/" && touch "/var/log/hs-api/debug.log"'

COPY ./ /root/
WORKDIR /root/

# install dependencies
RUN pip install -U pip &&\
    pip install -U pipenv &&\
    pipenv install &&\
    source .env.sh

# start background celery worker
# TODO: find a way to substitute `LOGS_DIR`
CMD pipenv run celery -l info\
    -f "/var/log/hs-api/celery.log" -A api worker -D &&\
    pipenv run ./manage.py migrate &&\
    pipenv run ./manage.py runserver 0:8000
