version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7
    ports:
      - "5672:5672"
  api:
    container_name: api
    # image: url to uploaded docker image
    build:
      context: ./
      args:
        LOGS_DIR: /var/log/hs-api
    env_file:
      - .env
    volumes:
      - ./:/opt/api/
    ports:
      - "8000:8000"
