# Generated by Django 2.2.4 on 2019-09-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='banner_image',
            field=models.URLField(default='https://random.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='min_team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('hackathon', 'hackathon'), ('competitive coding', 'competitive coding'), ('sql', 'sql'), ('machine learning', 'machine learning'), ('arena', 'arena'), ('virtual', 'virtual')], default='sql', max_length=100),
            preserve_default=False,
        ),
    ]
