# Generated by Django 2.2.3 on 2019-07-27 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('user', '0003_auto_20190616_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('one_time_code', models.CharField(max_length=8)),
                ('expires_at', models.DateTimeField()),
                ('blocked_until', models.DateTimeField(null=True)),
                ('attempts_used', models.IntegerField(default=0)),
                ('resends_used', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
        ),
    ]
